---
destination : ./_site/ 
auto        : false
lsi         : false
highlight   : pygment
permalink   : none
markdown    : kramdown 

maruku:
    use_divs: true
    use_tex: true
    png_engine : blahtex
    png_dir    : images/latex/
    png_url    : /images/latex/

    
production_url : http://www.hongyusu.com
